#!/usr/bin/env python3
#
# This file is part of obslogd.
#
# obslogd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# obslogd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with obslogd.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for writing messages into the observatory log database"""

# pylint: disable=invalid-name

import os
import sys
import warwick.observatory as observatory

SCRIPT_NAME = os.path.basename(sys.argv[0])

def print_usage(name):
    """Prints the utility help"""
    print('Usage: {} [info|warning|error] table message'.format(name))
    return 1

if __name__ == '__main__':
    if len(sys.argv) < 4:
        sys.exit(print_usage(SCRIPT_NAME))

    table = sys.argv[2]
    message = ' '.join(sys.argv[3:])
    if sys.argv[1] == 'info':
        sys.exit(observatory.log.info(table, message))
    elif sys.argv[1] == 'warning':
        sys.exit(observatory.log.warning(table, message))
    elif sys.argv[1] == 'error':
        sys.exit(observatory.log.error(table, message))

    # Command not found
    sys.exit(print_usage(SCRIPT_NAME))

